experiment:
  dt: 0.05    # simulation timestep
  duration: 10.0  # total duration in seconds
  mode: "doublebeat"    # "sensorimotor" or "beat"
  random_phase: false
  n_training_rounds: 100
  name: "doublebeat_exp"
  random_seed: 111    # random seed for initializing the weights
  tempo: 0.5  # seconds between beats
network:
  associative_size: 32
  inference_learning_rate: 0.1
  n_inference_steps: 20
  vestibular_size: 1
  weight_learning_rate: 0.05
saving:
  base_dir: "experiments"
  log_every: 10  # steps between logging
testing:
  n_inference_rounds: 1  # number of inference rounds during testing
  test_duration: 20.0      # duration of each test sequence in seconds
